config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'links#new'
  resources :links, only: [:new, :create]

  get '/:hash', to: 'redirects#perform', constraints: { hash: /\w+/ }, as: :perform_redirect
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates_presence_of :href
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  unless Rails.env.development?
    rescue_from ActionController::RoutingError, ActiveRecord::RecordNotFound, with: :render_404
  end

  private

  def render_404
    respond_to do |format|
      format.html { render file: 'public/404.html', layout: false, status: 404 }
      format.all { render nothing: true, status: 404 }
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def new; end

  def create
    link = Link.create!(href: params[:href])
    @hash = UrlShortener.encode(link.id)
  end
end

app/controllers/redirects_controller.rb
class RedirectsController < ApplicationController
  def perform
    id = UrlShortener.decode(params[:hash])
    href = Link.find(id).href

    redirect_to href
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= t('title')
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = yield

app/views/links/create.js.haml
:plain
  $('#short_url').val("#{perform_redirect_url(@hash)}")

app/views/links/new.html.haml
.url-container
  %h1.title= t('.title')
  %span#message
  = form_tag links_path, remote: true do
    = text_field_tag :href, '', class: 'url-input'
    = submit_tag t('.shrink'), class: 'url-button'
  = text_field_tag :short_url, '', readonly: true, class: 'url-input'
  %button{ type: 'button', id: 'copy_to_clipboard', class: 'url-button' }= t('.copy')